🤔
zvuc/thinking_face pull request #2
Opened 2017-09-27 06:29 UTC by kiding

🤔

2017-09-27 06:43 UTC, zvuc commented
🤔

2017-09-27 06:44 UTC, zvuc requested changes
🤔

2017-09-27 06:44 UTC, zvuc commented on README.md
> +> 🤔
🤔

2017-09-27 06:48 UTC, kiding commented on README.md
> +> 🤔
🤔

2017-09-27 12:34 UTC, teslamint commented
🤔 ?

2017-09-28 09:56 UTC, kiding commented
🤔

2017-09-28 09:57 UTC, zvuc approved these changes
🤔

2017-09-28 09:57 UTC, merged